//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aghaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string passwod { get; set; }
        public Nullable<decimal> contact { get; set; }
        public string address { get; set; }
    }
}
