//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aghaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public service()
        {
            this.requests = new HashSet<request>();
            this.worker_Portfolio = new HashSet<worker_Portfolio>();
        }
    
        public int Id { get; set; }
        public string service_type { get; set; }
        public int no_of_workers { get; set; }
        public string description { get; set; }
        public int cid { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<worker_Portfolio> worker_Portfolio { get; set; }
    }
}
