//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aghaApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_Portfolio
    {
        public worker_Portfolio()
        {
            this.Availability_Slots = new HashSet<Availability_Slots>();
            this.requests = new HashSet<request>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string cnic { get; set; }
        public string contact1 { get; set; }
        public string address { get; set; }
        public string experience_ { get; set; }
        public string contact2 { get; set; }
        public int sid { get; set; }
    
        public virtual ICollection<Availability_Slots> Availability_Slots { get; set; }
        public virtual ICollection<request> requests { get; set; }
        public virtual service service { get; set; }
    }
}
